model:
  name: 'yolo.yaml'
  task: 'train'
  verbose: True
  device: '0'
  seed: 0
  deterministic: True
  project: 'runs/train' # (str, optional) project name
  folder: 'exp' # (str, optional) experiment name, results saved to 'project/name' directory
  batch: 128
  data: 'dataset.yaml'
  weights: ''
  imgsz: 640
  optim: 'SGD'
  cos_lr: False
  flat_cos_lr: False
  fixed_lr: False
  epochs: 10
  freeze: [0]
  sync_bn: True
  cache: '' # image cache 'ram' or 'disk'
  workers: 8
  close_mosaic: 15
  patience: 100 # EarlyStopping patience (epochs without improvement)
  multi_scale: False
  save_period: -1
  nosave: False

hyp:
  lr0: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
  lrf: 0.01  # final OneCycleLR learning rate (lr0 * lrf)
  momentum: 0.937  # SGD momentum/Adam beta1
  weight_decay: 0.0005  # optimizer weight decay 5e-4
  warmup_epochs: 3.0  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  box: 7.5  # box loss gain
  cls: 0.5  # cls loss gain
  cls_pw: 1.0  # cls BCELoss positive_weight
  obj: 0.7  # obj loss gain (scale with pixels)
  obj_pw: 1.0  # obj BCELoss positive_weight
  dfl: 1.5  # dfl loss gain
  iou_t: 0.20  # IoU training threshold
  anchor_t: 5.0  # anchor-multiple threshold
  # anchors: 3  # anchors per output layer (0 to ignore)
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4  # image HSV-Value augmentation (fraction)
  degrees: 0.0  # image rotation (+/- deg)
  translate: 0.1  # image translation (+/- fraction)
  scale: 0.9  # image scale (+/- gain)
  shear: 0.0  # image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.0  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
  mosaic: 1.0  # image mosaic (probability)
  mixup: 0.15  # image mixup (probability)
  copy_paste: 0.3  # segment copy-paste (probability)
  # label_smoothing: 0.0